SET_LINKS = 0
ADD_LINKS = 1
GET_LINKS = 2


ADD_MONITOR = 10
ADD_SCRAPER = 11
ADD_MONITOR_SCRAPER = 12

STOP = 50
STOP_MONITOR = 51
STOP_SCRAPER = 52
STOP_MONITOR_SCRAPER = 53
STOP_MONITOR_MANAGER = 54


GET_MONITOR_STATUS = 100
GET_SCRAPER_STATUS = 101
GET_MONITOR_SCRAPER_STATUS = 102

SOCKET_PATH = "/tmp"
CRASH_WEBHOOK = ""
